language: c
sudo: required
dist: trusty
compiler: gcc
before_script:
  - sudo apt-get install doxygen cmake
  - cmake .
script: make
after_success:
  - >-
    if [[ "$TRAVIS_BRANCH" = "master"]] ; then
      cd $PROJECT_DIR_ABS
      source ci/setup-ssh.sh || travis_terminate 1
      ci/generateDocumentation.sh || travis_terminate 1
    fi
